/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-07-01 18:33:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"page-error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Weather App - CodingWallahSir</title>\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"style.css\" />\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  font-family: \"Ubuntu\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  height: 100vh;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  background: linear-gradient(to right,  #2b40ff,#07121a);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mainContainer {\r\n");
      out.write("  width: 25rem;\r\n");
      out.write("  height: auto;\r\n");
      out.write("  border-radius: 1rem;\r\n");
      out.write("  background: #fff;\r\n");
      out.write("  box-shadow: 0 14px 28px rgba(0,0,0,0.25), \r\n");
      out.write("			0 10px 10px rgba(0,0,0,0.22);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchInput {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  padding: 1rem 1rem;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchInput input {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 2rem;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  font-size: 1rem;\r\n");
      out.write("  color: #525050;\r\n");
      out.write("  padding: 0.2rem 0.5rem;\r\n");
      out.write("  border-radius: 1.5rem;\r\n");
      out.write("  border: 1px solid #b3b3b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchInput input:focus {\r\n");
      out.write("  border: 1px solid #9c9dde;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchInput button {\r\n");
      out.write("  width: 2.2rem;\r\n");
      out.write("  height: 2rem;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  color: #9b9b9b;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  margin-left: 0.4rem;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  border: 1px solid #b3b3b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchInput button:hover {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  background-color: #9c9dde;\r\n");
      out.write("  border: 1px solid #9c9dde;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".weatherIcon {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  padding-top: 0.5rem;\r\n");
      out.write("  padding-bottom: 0.5rem;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".weatherIcon img {\r\n");
      out.write("  max-width: 100%;\r\n");
      out.write("  width: 8rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".weatherDetails .temp{\r\n");
      out.write(" font-size: 2rem;\r\n");
      out.write("}\r\n");
      out.write(".cityDetails {\r\n");
      out.write("  color: #323232;\r\n");
      out.write("  font-size: 2.5rem;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-bottom: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cityDetails .date {\r\n");
      out.write("  color: #323232;\r\n");
      out.write("  font-size: 1.5rem;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-bottom: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".windDetails {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  margin-top: 1rem;\r\n");
      out.write("  margin-bottom: 1.5rem;\r\n");
      out.write("  justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".windDetails .humidityBox {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  font-size: 1rem;\r\n");
      out.write("  color: #323232;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".windDetails .humidity .humidityValue {\r\n");
      out.write(" text-align: center;\r\n");
      out.write("  font-size: 2rem;\r\n");
      out.write("  color: #323232;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".windDetails .humidityBox img {\r\n");
      out.write("  max-height: 3rem;\r\n");
      out.write("  margin-right: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".windDetails .windSpeed {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  font-size: 1rem;\r\n");
      out.write("  color: #323232;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".windDetails .windSpeed img {\r\n");
      out.write("  max-height: 3rem;\r\n");
      out.write("  margin-right: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("image-logo{\r\n");
      out.write("        height: auto;\r\n");
      out.write("        width: auto;\r\n");
      out.write("        filter: drop-shadow(20px 10px 10px black);\r\n");
      out.write("      }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mainContainer\">\r\n");
      out.write("     <form action=\"FetchCity\" method=\"post\" class=\"searchInput\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"Enter City Name\" id=\"searchInput\"  name=\"city\"/>\r\n");
      out.write("            <button id=\"searchButton\"><i class=\"fa-solid fa-magnifying-glass fa-beat\"></i></button>\r\n");
      out.write("      </form>\r\n");
      out.write("        <div class=\"weatherDetails\">\r\n");
      out.write("            <div class=\"weatherIcon\">\r\n");
      out.write("                <img src=\"\" alt=\"Clouds\" id=\"weather-icon\">\r\n");
      out.write("                <h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${temperature}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" °C</h2>\r\n");
      out.write("                 <input type=\"hidden\" id=\"wc\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherCondition}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> </input>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"cityDetails\">        \r\n");
      out.write("                <div class=\"desc\"><strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></div>\r\n");
      out.write("                <div class=\"date\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"windDetails\">\r\n");
      out.write("            	<div class=\"humidityBox\">\r\n");
      out.write("            	<img src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhgr7XehXJkOPXbZr8xL42sZEFYlS-1fQcvUMsS2HrrV8pcj3GDFaYmYmeb3vXfMrjGXpViEDVfvLcqI7pJ03pKb_9ldQm-Cj9SlGW2Op8rxArgIhlD6oSLGQQKH9IqH1urPpQ4EAMCs3KOwbzLu57FDKv01PioBJBdR6pqlaxZTJr3HwxOUlFhC9EFyw/s320/thermometer.png\" alt=\"Humidity\">\r\n");
      out.write("                <div class=\"humidity\">\r\n");
      out.write("                   <span>Humidity </span>\r\n");
      out.write("                   <h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${humidity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("% </h2>\r\n");
      out.write("                </div>\r\n");
      out.write("               </div> \r\n");
      out.write("               \r\n");
      out.write("                <div class=\"windSpeed\">\r\n");
      out.write("                    <img src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiyaIguDPkbBMnUDQkGp3wLRj_kvd_GIQ4RHQar7a32mUGtwg3wHLIe0ejKqryX8dnJu-gqU6CBnDo47O7BlzCMCwRbB7u0Pj0CbtGwtyhd8Y8cgEMaSuZKrw5-62etXwo7UoY509umLmndsRmEqqO0FKocqTqjzHvJFC2AEEYjUax9tc1JMWxIWAQR4g/s320/wind.png\">\r\n");
      out.write("                    <div class=\"wind\">\r\n");
      out.write("                    <span>Wind Speed</span>\r\n");
      out.write("                    <h2> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${windSpeed}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" km/h</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("	var weatherIcon = document.getElementById(\"weather-icon\");\r\n");
      out.write("	\r\n");
      out.write("	var val = document.getElementById(\"wc\").value;\r\n");
      out.write("	  switch (val) {\r\n");
      out.write("      case 'Clouds':\r\n");
      out.write("          weatherIcon.src = \"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiwFTkt5z_dxU6w1UnS1PxiZV3HDiPGsAW5Lrsp09MnlCmkQre9GzO8MnGytaaY1eZoqBN6SMJ4U578_uDtiuXswovr1T3o-Kt5KK0mlN_zC0RDodJFaKHQ3Uk-HIZ3vuMvAKNJi8DDFwWA7F6BOxz78Oh-UePwJTuc3PG0ZIZypPE1xlMPl5z46joaEw/s320/Clouds.png\";\r\n");
      out.write("          break;\r\n");
      out.write("      case 'Clear':\r\n");
      out.write("          weatherIcon.src = \"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj7pmzNCftryAfpa1YBSzVeYtjgxDQnw09Ug0HVV47J8GEtHPYTH9hJgZ2M1k0YgE0pcZ1qekr4C14zyPCiVuQAfXLClK8Ww3hYB6v77yElP7Lo5BnUKo4n-w6yB17FAbw51WST6YKS0GMwyA4fYNxOZxEyNL6HhUfFRgVhOW0GyRdBRriMHFQ-qfh4cA/s320/sun.png\";\r\n");
      out.write("          break;\r\n");
      out.write("      case 'Rain':\r\n");
      out.write("          weatherIcon.src = \"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgDW_NdwvxV796rkFf43qmUDiTQePn5dg7PDfn1SijfpjtB0AWJMBcifU6LWyW7iOtjZhfqIJnKEGQ1PwbbXS7NoKMSAmvy7i2ljWXMYLue3EBIBBR2qTFbs6QCe5eoFr2CU9WzCVJ8u0J3z3eAo3Ajv1LXamZASFtbj9sA_gD-Kp3hfgAk17Xh17RoLQ/s320/rainy.png\";\r\n");
      out.write("          break;\r\n");
      out.write("      case 'Mist':\r\n");
      out.write("          weatherIcon.src = \"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgVpL23l0t1U_ibWi01TFcHMF6J_t-9Ada5PavGlwG4M_mKIcx0pV1md9SN9ip1d84NaVowml5Do16XO3nsuttnM2-Ov05d-wCjEYjdzaOYfKvijw8k6Hfj9pOiPyEZTp2W20EPbTeONTgJE2Rdxs4KZUfg6f2PmbMF1094NcqJ7DwSFUQwYiRmVCNvuA/s320/mist.png\";\r\n");
      out.write("          break;\r\n");
      out.write("      case 'Snow':\r\n");
      out.write("          weatherIcon.src = \"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj-P3iT_uQK95qFY4h7QGdEtbRc1aVQo9BZy0ZWyPBvCNrP-4wnRStw0xYj9e4xa4ZlYISeNZqVJ33UP4YukR4jBennDD_obIN4QxYNZHdzG_z6_MNL2U08wMXwdFhtfvitW5LGiHgrwMJFC8QJFqbSO3woGSBqOdagGxaEQ20_S31Gc-GYL4vYzPzaPw/s320/snow.png\";\r\n");
      out.write("          break;\r\n");
      out.write("      case 'Haze':\r\n");
      out.write("          weatherIcon.src = \"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjld66Ia5g_hpBn3Impi3zzOBHqWkjQInGLxTb2uXksuCsrkQU8HjlVyLobEJEGg8fRSIxeFzldGEHUmWcaiZBwAcRy4dGDpFX1BjTSB56qmBjW5tEW3RSC9_mCuLU_a8RuXchxGY7Oc8HLLl-IfaDW19Z0ZJJfNae9tECXRIyEu7rmJ3da08z8cI-phw/s320/haze.png\";\r\n");
      out.write("          break;\r\n");
      out.write("  }\r\n");
      out.write("	  </script>\r\n");
      out.write("	  \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
